### ISSUE TITLE
很棒的教程，感谢分享！【从0开始超详细部署教程】链接好像失效了

### ISSUE THREAD

**Issue by rujiewu** [inannan423/orange-nan-mini_program#3]
![image](https://user-images.githubusercontent.com/43574852/180167973-989c1380-e808-4f3a-aa1d-ab2df09c3f66.png)

**Comment by inannan423** [comment]
感谢提醒！！！已经改啦！[从0开始超详细部署教程](https://jetzihan.netlify.app/docs/%E5%89%8D%E7%AB%AF/%E5%89%8D%E7%AB%AF%E6%8A%80%E5%B7%A7/%E6%83%85%E4%BE%A3%E5%95%86%E5%9F%8E%E5%BE%AE%E4%BF%A1%E5%B0%8F%E7%A8%8B%E5%BA%8F%E9%83%A8%E7%BD%B2%E8%AF%A6%E7%BB%86%E6%95%99%E7%A8%8B)

**Comment by inannan423** [comment]
如果觉得有帮助，请给我一个Star！谢谢！

> ![image](https://user-images.githubusercontent.com/43574852/180167973-989c1380-e808-4f3a-aa1d-ab2df09c3f66.png)

**Comment by rujiewu** [comment]
谢谢！已经star！
